Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 349, in kick
    [row[1] for row in self.db.get_all_members]:

TypeError: 'method' object is not iterable
Occured at: 04:48:19.204860Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 149, in list_members
    table = PrettyTable(["ID", "Name"])

NameError: name 'PrettyTable' is not defined
Occured at: 04:49:10.688596Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 353, in kick
    await self.kick_member(person)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 334, in kick_member
    await person.remove_roles(*member_roles, reason = "Kicked from the outfit")

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\member.py", line 660, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)

AttributeError: 'NoneType' object has no attribute 'id'
Occured at: 04:52:24.937948Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 163, in get_attendance
    table_path = await self.db.get_att_per_member()

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 211, in get_att_per_member
    col_labels = ["Name", "Attendance (%)", "Away (yes or no)"]

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\mestils.py", line 51, in create_table
    pyplot.savefig(path, bbox_inches = new_boundary_box)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\pyplot.py", line 723, in savefig
    res = fig.savefig(*args, **kwargs)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backend_bases.py", line 2105, in print_figure
    **kwargs)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 535, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\cbook\__init__.py", line 418, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\cbook\__init__.py", line 403, in to_filehandle
    fh = open(fname, flag, encoding=encoding)

FileNotFoundError: [Errno 2] No such file or directory: './Images/table_at_16.40.43.png'
Occured at: 16:40:44.539032Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 164, in get_attendance
    table_path = await self.db.get_att_per_member()

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 211, in get_att_per_member
    col_labels = ["Name", "Attendance (%)", "Away (yes or no)"]

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\mestils.py", line 47, in create_table
    points = table.get_window_extent(figure._cachedRenderer).get_points()

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\table.py", line 458, in get_window_extent
    self._update_positions(renderer)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\table.py", line 592, in _update_positions
    self._auto_set_font_size(renderer)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\table.py", line 537, in _auto_set_font_size
    size = cell.auto_set_font_size(renderer)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\table.py", line 111, in auto_set_font_size
    required = self.get_required_width(renderer)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\table.py", line 166, in get_required_width
    l, b, w, h = self.get_text_bounds(renderer)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\table.py", line 160, in get_text_bounds
    bbox = self._text.get_window_extent(renderer)

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\text.py", line 903, in get_window_extent
    raise RuntimeError('Cannot get window extent w/o renderer')

RuntimeError: Cannot get window extent w/o renderer
Occured at: 01:48:56.768749Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 164, in get_attendance
    table_path = await self.db.get_att_per_member()

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 206, in get_att_per_member
    for name, average, away in zip(members, averages, aways)]

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 205, in <listcomp>
    table_rows = [(name, average, away)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 201, in <lambda>
    averages = map( lambda row: int( round( row[0] *100, 0 ) ), rows )

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
Occured at: 01:50:19.239763Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 164, in get_attendance
    table_path = await self.db.get_att_per_member()

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 211, in get_att_per_member
    for name, average, away in zip(members, averages, aways)]

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 210, in <listcomp>
    table_rows = [(name, average, away)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 205, in <lambda>
    if rows[0] is not None else 0

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
Occured at: 02:02:58.816391Traceback (most recent call last):

  File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Cogs\Attendance.py", line 164, in get_attendance
    table_path = await self.db.get_att_per_member()

  File "C:\Users\Sam\Desktop\DTWM-Discord-Bot\DTWM-Discord-Bot\Utils\AttendanceDB.py", line 214, in get_att_per_member
    sorted_rows = sorted(table_rows, lambda row: row[0])

TypeError: must use keyword argument for key function
Occured at: 02:30:06.819086